language: python
python:
- "3.4"
before_script:
- psql -c 'create database monkeyapp;' -U postgres
- export CHROME_BIN='chromium-browser'
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- pip install -r requirements.txt
- python create_db.py
- npm install
- npm start &
- node_modules/.bin/webdriver-manager update
- sleep 1
script:
- py.test backend_tests/
- node_modules/karma/bin/karma start karma.conf.js  --single-run --firefox
- node_modules/protractor/bin/protractor e2e-tests/protractor.conf.js